sudo: false
language: elixir
elixir: '1.7.2'
otp_release: '21.0'

cache:
  directories:
    - _build
    - deps
env:
  - MIX_ENV=test

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix deps.compile

script:
  - mix credo --strict
  - mix test
  # - mix dialyzer --halt-exit-status
  - mix coveralls.travis