sudo: false
language: elixir
elixir: '1.7.2'
otp_release: '21.0'

cache:
  directories:
    - _build
    - deps
env:
  - MIX_ENV=test

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix deps.compile

script:
  - mix credo --strict
  - mix test
  - mix coveralls.travis
  - MIX_ENV=dev mix docs 

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: "doc/"
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master